### ISSUE TITLE
Day, month, year data type warning

### ISSUE THREAD

**Issue by ethankale** [mundl/lfstat#1]
The package allows you to create an lfobj as long as you have day, month, and year columns, but it doesn't check for the data type.  If you happen to create an lfobj with those columns as characters instead of as numeric (easy to do if you're using format() to convert from a date field), some functions will work, but others (hydrograph()) will not.

Maybe a warning on import to convert these fields to numeric?  Or a check & autoconvert on import?

**Comment by mundl** [comment]
Thanks for reporting, this is resolved with commit 0e9e09a. 

`createlfobj()` will try to convert the columns to numeric(). If this introduces additional NA values, an error is risen. 

eg, this should work:
`createlfobj(data.frame(year=1999, month="3", day=1:10, flow=5))`

wheras this fails:
`createlfobj(data.frame(year=1999, month="march", day=1:10, flow=5))`
