### ISSUE TITLE
Error when using evfit, evqualtile or ev_return_Period

### ISSUE THREAD

**Issue by Rif08** [mundl/lfstat#2]
Hello, 

I am a beginner user in R and I am hoping you can help. 

I am using R R-3.4.2 with R studio1.1.383. I am attempting to learn the lfstats package and I get the following error 1.1.383 when trying to use evfit, evqualtile or ev_return_Period. 

Error in samlmu(xx) : object 'RegSym_samlm' not found

The issue seems to be with the samlmu command,  as the samlmu.s seems to work fine in the lmoments package. Id there a way of correcting the error or using the samlmu.s for the evfit command ? 

Forgive my ignorance, my skills are very basic at this stage any help you can provide will be appreciated. 

Best Regards, 

R

**Comment by mundl** [comment]
Hi Rif08,

thank you for registering to github and reporting an issue. 

Unfortunately I cannot reproduce the error you mentioned with the example in the manpage of `evfit()` with R 3.4.2, lmom 2.6 and lfstat 0.9.4. If your packages are outdated, try updating all your installed packages with:

`update.packages(ask = FALSE)`

It would be very helpful I you could provide a reproducible example (data + code) leading to the error. In case the error has to do with your dataset and you cannot publicly share it, please send it (as an RData file) to t.gauster@boku.ac.at. 

Furthermore, please attach the output of `sessionInfo(). 

Regards,
Tobias

**Comment by Rif08** [comment]
Hi Tobias, 

Thank you for the prompt response, the error was as a result of the lmom package not being able to access the compiled Fotran code. A reinstall of the lmom package has fixed the issue. 

I thank you for your quick response and assistance. 

Best Wishes, 
Rif08
