### ISSUE TITLE
Import gauging station name and coordinates with readlfdata command

### ISSUE THREAD

**Issue by giacfalk** [mundl/lfstat#3]
I am importing GRDC data into R using the readlfdata package, which works great. However, I would like to import it along with the metadata, i.e. station name, coordinates, etc, since I am handling a large number of stations. Is this possible?

**Comment by mundl** [comment]
Hi,

I am the new maintainer of lfstat and I do not have a GRDC file at hand. If you could send me 2-5 files I could implement importing the metadata. 

Regards,
Tobias
t.gauster@boku.ac.at

**Comment by mundl** [comment]
However, if you just need coordinates a look at Claudia Vitolos R package hddtools might be of help.

The following code imports the metadata (zip file hosted here: ftp://ftp.bafg.de/pub/REFERATE/GRDC/catalogue/grdc_stations.zip) of all currently available GRDC stations into a `data.frame`. 

```
library(hddtools)
stations <- catalogueGRDC()
```
