### ISSUE TITLE
Multiple input files 

### ISSUE THREAD

**Issue by solomonsg** [mundl/lfstat#4]
Dear Tobias and all,

I found the package very useful and wanted to apply for multiple files about 10000 points available in NetCDF in a way as a loop. like read all files in a directory and compute certain tasks such as droughts find_droughts(ray) and save it into CSV. 

Best regards,

Solomon

**Comment by mundl** [comment]
Dear Solomon,

are you asking for an example of how to do this in **lfstat**? If so, it would be helpful if you can attach an example NetCDF file and a more precise description of the results you want to save as a csv file.

Best,
Tobias

**Comment by solomonsg** [comment]
Dear Tobias,

here is an example .nc file and i have about 10000 files. So the idea is there is a possibility to apply a kind of loop in the folder something line read nc files in the folder and compute lfstat (find droughts) and save it to csv. 
[Nwokuy.zip](https://github.com/mundl/lfstat/files/3615861/Nwokuy.zip)

Best regards,

Solomon

**Comment by mundl** [comment]
Hi Solomon,

this is not a lfstat question or issue, more a general question about data structures and R programming. 

```
library(lfstat)
library(ncdf4)
library(tidyverse)

# dicrectory of netcdf input files
dir <- "./data/solomon/"
files <- list.files(path = dir, pattern = ".*\\.nc$",
                    ignore.case = TRUE, full.names = TRUE)

outdir <- file.path(dir, "droughts")
dir.create(outdir)


# helper function to extract the time series of your netcdf file
ncdf_timeseries <- function(filename)
{
  # open input file
  nc <- nc_open(filename)
  origin <- sub("days since ", "", nc$dim$time$units)

  x <- xts(
    data.frame(value = ncvar_get(nc, "Qout")),
    order.by = as.Date(nc$dim$time$vals, origin = origin)
  )

  nc_close(nc)

  return(x)
}
```

# Solution using a loop:
```
for (i in seq_along(files))
{
  # extract netcdf time series as xts object
  river <- ncdf_timeseries(filename = files[i])

  # your computation ...
  droughts <- summary(find_droughts(river))

  fn <- file.path(outdir, sub("\\.nc$", ".csv", basename(files[i]),
                              ignore.case = TRUE))
  # write out csv file
  write_csv(droughts, path = fn)
}
```


# Alternate solution using list-columns
If memory size is not an issue you can keep all the results in list columns. This might be helpful when comparing the results.
```
data <- tibble(file = files) %>%
  mutate(river = sub("\\..*$", "", basename(files)),
         Qout = map(file, ncdf_timeseries),
         droughts = map(Qout, find_droughts, threshold = "Q80"),
         pooled = map(droughts, pool_sp),
         tbl = map(pooled, summary))

data$tbl[[1]]

# get rid of list-columns, reshape into long format
long <- data %>%
  select(river, tbl) %>%
  unnest()

# strip chart of drought durations
ggplot(long) +
  geom_segment(aes(x = start, xend = end, y = river, yend = river,
                   col = duration), size = 4) +
  scale_color_gradient2() +
  theme_bw()

# distribution of drought deficit volumes
ggplot(long) +
  geom_density(aes(x = volume)) +
  facet_wrap(facets = vars(river))
```
I am closing this issue as it is not really related to the R package **lfstat**. If you have further questions please email me. 

Best,
Tobias

**Comment by solomonsg** [comment]
Dear Tobias,

Thanks a lot and it worked in the way i wanted. 
is it still possible to add other factors such as moving window (e.g., 30 days) and event and inter-event duration to specify minimum drought duration (e.g., 15 days) and minimum inter-event duration (e.g., 10 days). 

droughts <- find_droughts(river, threshold=0.2, varying = "monthly" )

Best regards,

Solomon

**Comment by mundl** [comment]
Hi,

filtering (dropping minor droughts) is achieved using the argument `drop.minor`.

```
data(ngaruroro)
ng <- as.xts(ngaruroro)
ng <- ng["1986::1990", ]

drought <- find_droughts(ng)
summary(drought, drop_minor = c(duration = 5, volume = 0))
summary(drought, drop_minor = c(volume = "0.5%", duration = 5))
```

The other concept is called 'pooling' of droughts. Please have a look at `?pooling`. **lfstat** supports pooling based on a inter-event time and inter-event volume criterion. Furthermore also pooling with Sequent Peak algorithm (`pool_sp`) is provided. 

Best,
Tobias
