### ISSUE TITLE
package ‘Ifstats’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by precinoto** [mundl/lfstat#5]
Hi! I need to use the Ifstats package, but even though I have just installed Rtools, I receive this error message:

install.packages("Ifstats", type = "source")
Installing package into ‘C:/Users/raiza/OneDrive/Documentos/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  **package ‘Ifstats’ is not available (for R version 4.0.2)**

Then, I installed the newest version of both R and Rstudio, and doesn't work neither:
install.packages("Ifstats", type = "source")
Installing package into ‘C:/Users/raiza/OneDrive/Documentos/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  **package ‘Ifstats’ is not available for this version of R**

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

What should I do?
Is there any new version of Ifstats to use lately?

**Comment by mundl** [comment]
The package is named **lfstat** without an s at the end. 

`
install.packages("Ifstats", type = "source")
`

should solve you problem.
